### ISSUE TITLE
Unable to call watson Assistant V1 API behind http proxy

### ISSUE THREAD

**Issue by kokoji** [watson-developer-cloud/node-sdk#901]
I have similar issue reported already by another user . I am developing a node.js app that calls watson assistant v1 api (message). Since my nodeapp runs behind proxy server, its not able to call watson api. There is no mechanism to specify proxy server to the request wrapper used in the ibm-watson node module. I tried setting http proxy via npm, still it didn't resolve the issue. Can this be fixed?

I have checked that I can call by curl command, and I have checked that I can call by request  module of node.js,  but I cannot call by ibm-watson assistant v1 module of node.js.

I have done some commands below. 
export HTTP_PROXY=http://xx.xx.xx.xx:xxxx
export HTTPS_PROXY=http://xx.xx.xx.xx:xxxx
npm -g config set proxy http://xx.xx.xx.xx:xxxx
npm -g config set https-proxy http://xx.xx.xx.xx:xxxx

**Comment by kokoji** [comment]
The error message is below:
Error: Response not received. Body of error is HTTP ClientRequest object
   at formatError (/var/www/node/ApplTest/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:115:17)
   at /var/www/node/ApplTest/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:267:19
   at <anonymous>
 message: ‘Response not received. Body of error is HTTP ClientRequest object’,
 body:
  Writable {
    _writableState:
     WritableState {
       objectMode: false,
       highWaterMark: 16384,
       finalCalled: false,
       needDrain: false,
       ending: false,
       ended: false,
       finished: false,
       destroyed: false,
       decodeStrings: true,
       defaultEncoding: ‘utf8’,
       length: 0,
       writing: false,
       corked: 0,
       sync: true,
       bufferProcessing: false,
       onwrite: [Function: bound onwrite],
       writecb: null,
       writelen: 0,
       bufferedRequest: null,
       lastBufferedRequest: null,
       pendingcb: 0,
       prefinished: false,
       errorEmitted: false,
       bufferedRequestCount: 0,
       corkedRequestsFree: [Object] },
    writable: true,
    domain: null,
    _events:
     { response: [Function: handleResponse],
       error: [Function: handleRequestError] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options:
     { maxRedirects: 21,
       maxBodyLength: 10485760,
       protocol: ‘https:‘,
       path: ’https://iam.cloud.ibm.com/identity/token',
       method: ‘post’,
       headers: [Object],
       agent: [Object],
       auth: undefined,
       hostname: ‘xx.xx.xx.xx’,
       port: ‘8080’,
       nativeProtocols: [Object],
       pathname: ‘https://iam.cloud.ibm.com/identity/token’ },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 135,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function],
    _currentRequest:
     ClientRequest {
       domain: null,
       _events: [Object],
       _eventsCount: 6,
       _maxListeners: undefined,
       output: [],
       outputEncodings: [],
       outputCallbacks: [],
       outputSize: 0,
       writable: true,
       _last: true,
       upgrading: false,
       chunkedEncoding: false,
       shouldKeepAlive: false,
       useChunkedEncodingByDefault: true,
       sendDate: false,
       _removedConnection: false,
       _removedContLen: false,
       _removedTE: false,
       _contentLength: null,
       _hasBody: true,
       _trailer: ‘’,
       finished: true,
       _headerSent: true,
       socket: [Object],
       connection: [Object],
       _header: ‘POST https://iam.cloud.ibm.com/identity/token HTTP/1.1¥r¥nAccept: application/json, text/plain, */*¥r¥nContent-Type: application/x-www-form-urlencoded¥r¥nAuthorization: Basic Yng6Yng=¥r¥nUser-Agent: axios/0.18.0¥r¥nContent-Length: 135¥r¥nhost: iam.cloud.ibm.com¥r¥nConnection: close¥r¥n¥r¥n’,
       _onPendingData: [Function: noopPendingOutput],
       agent: [Object],
       socketPath: undefined,
       timeout: undefined,
       method: ‘POST’,
       path: ‘https://iam.cloud.ibm.com/identity/token’,
       _ended: false,
       res: null,
       aborted: undefined,
       timeoutCb: null,
       upgradeOrConnect: false,
       parser: null,
       maxHeadersCount: null,
       _redirectable: [Circular],
       [Symbol(outHeadersKey)]: [Object] },
    _currentUrl: ‘https://xx.xx.xx.xx:8080/https://iam.cloud.ibm.com/identity/token’ } }

**Comment by dpopp07** [comment]
Hi @kokoji, try reading the [documentation for `axios`](https://github.com/axios/axios#request-config), which is our underlying request library. All `axios` request options are settable via the **constructor** of the service object. Try the `proxy` parameter and let me know how that goes.

**Comment by kokoji** [comment]
Hi @dpopp07 , thank you.
I would like to try axios, but it seems that the ibm-watson/assistant/v1.js does not use axios module.
How do I combine ibm-watson/assistant/vi.js and axios module?

**Comment by kokoji** [comment]
In my understanding, node.js application uses proxy automatically, because I done the command below.
"export HTTP_PROXY=http://xx.xx.xx.xx:xxxx"
"export HTTPS_PROXY=http://xx.xx.xx.xx:xxxx"

I can use other api of Watson discovery service, without additional proxy setting in the code.
Why the api of assistant need the additional proxy settings in the code?
The OS of  server is RHEL v7.

**Comment by kokoji** [comment]
I could access Watson assistant from node.js through proxy server by https://github.com/watson-developer-cloud/node-sdk/issues/900#issuecomment-509106115.
But above is a workaround, so I need fix version.

**Comment by dpopp07** [comment]
@kokoji There is no need to combine axios and the sdk module - I just meant that the axios options are available in the constructor of the sdk. See [this comment](https://github.com/watson-developer-cloud/node-sdk/issues/900#issuecomment-509257669) in that other thread you mentioned.

There still may be a fix needed in the SDK, as I posted in that other issue. Stay tuned for the fix there

**Comment by dpopp07** [comment]
@kokoji There has been a fix released for this in `v4.3.2`. Try using [the approach described here](https://github.com/watson-developer-cloud/node-sdk#using-the-sdk-behind-a-corporate-proxy) and let me know if that solves your problem.

**Comment by kokoji** [comment]
It still doesn't work in my environment with module v4.3.2.
I need to do problem determination about this.

**Comment by kokoji** [comment]
By the way, I'd like to check for PD, what is your Node.js environment version? 
My Node.js environment is v8. 
I think it may need to update my Node.js environment.

**Comment by cobaltway** [comment]
We're experiencing the exact same error here with SpeechToTextV1.
Package version is 4.4.0.

**Comment by cobaltway** [comment]
OK we figured it; we were using the `HTTP_PROXY` value, which contains the `http://` prefix in the production env. An host without the prefix works fine.

Thanks for the reactive support.

**Comment by kokoji** [comment]
@dpopp07 Hi, it seems to be working correctly. Thank you!
